binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
combine_control_expr = true
comment_width = 120
condense_wildcard_suffixes = true
empty_item_single_line = true
fn_params_layout = "Compressed"
fn_single_line = true
force_explicit_abi = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
hard_tabs = true
imports_indent = "Block"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
indent_style = "Block"
match_block_trailing_comma = true
max_width = 120
merge_derives = true
newline_style = "Native"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
trailing_semicolon = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true

